server:
  port: 9055

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:userdetails-test
    username: sa
    password: